"""SQLite event journal, projections, repositories, and integrity checks."""

from .database import Database, initialize_database
from .event_store import EventRecord, EventStore, verify_rows
from .integrity import GENESIS_HASH, IntegrityReport
from .projections import ProjectionError, ProjectionStore
from .repositories import (
    ApprovalArgumentsUnavailableError,
    ApprovalError,
    ApprovalExpiredError,
    ApprovalMismatchError,
    ApprovalRecord,
    ApprovalRepository,
    ApprovalUnsafeActionError,
    ArtifactRecord,
    ArtifactRepository,
    BudgetRecord,
    BudgetRepository,
    ConflictError,
    MemoryRecord,
    MemoryRepository,
    MemoryValidationError,
    MessageRecord,
    MessageRepository,
    NotFoundError,
    RepositoryError,
    RunRecord,
    RunRepository,
    ToolCallRecord,
    ToolCallRepository,
    WorkItemRecord,
    WorkItemRepository,
)

__all__ = [
    "ApprovalArgumentsUnavailableError",
    "ApprovalError",
    "ApprovalExpiredError",
    "ApprovalMismatchError",
    "ApprovalRecord",
    "ApprovalRepository",
    "ApprovalUnsafeActionError",
    "ArtifactRecord",
    "ArtifactRepository",
    "BudgetRecord",
    "BudgetRepository",
    "ConflictError",
    "Database",
    "EventRecord",
    "EventStore",
    "GENESIS_HASH",
    "IntegrityReport",
    "MemoryRecord",
    "MemoryRepository",
    "MemoryValidationError",
    "MessageRecord",
    "MessageRepository",
    "NotFoundError",
    "ProjectionError",
    "ProjectionStore",
    "RepositoryError",
    "RunRecord",
    "RunRepository",
    "ToolCallRecord",
    "ToolCallRepository",
    "WorkItemRecord",
    "WorkItemRepository",
    "initialize_database",
    "verify_rows",
]
